# Generated by Django 4.1.2 on 2022-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscription_alter_userinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
