# Generated by Django 4.1.2 on 2022-10-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscription_subscription_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSubscriptionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_subscription_type', models.CharField(max_length=50)),
                ('new_subscription_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
